In [5]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def mean_squared_error(y_pred, y_true):
    return 0.5 * (y_pred - y_true) ** 2

def forward_pass(X, W1, b1, W2, b2):   
    hidden_input = np.dot(W1, X) + b1
    hidden_output = relu(hidden_input)
    final_input = np.dot(W2, hidden_output) + b2
    y_pred = final_input[0]

    return y_pred, hidden_output, hidden_input, final_input

def backward_pass(X, y_true, W1, b1, W2, b2, hidden_output, hidden_input, output_input, y_pred):
    """
    Parameters:
    X      : numpy array shape (3,)
    y_true : nilai target (0 atau 1)
    W1     : bobot input -> hidden (4, 3)
    b1     : bias hidden (4,)
    W2     : bobot hidden -> output (1, 4)
    b2     : bias output (1,)

    Returns:
    Tuple: (dW2, db2, dW1, db1) semua dalam bentuk numpy array
    """
    error = y_pred - y_true
    
    dW2 = error * hidden_output.reshape(1, -1)
    db2 = error
    
    d_hidden = error * W2.reshape(-1)
    d_hidden[hidden_input <= 0] = 0 
    
    dW1 = np.outer(d_hidden, X)
    db1 = d_hidden

    return dW2, db2, dW1, db1

def train_regression_3epoch():
    np.random.seed(100)
    
    X = np.array([1.0, 2.0, -1.0])
    y_true = 3.5
    
    learning_rate = 0.1
    
    W1 = np.random.randn(4, 3)
    b1 = np.random.randn(4)
    W2 = np.random.randn(1, 4)
    b2 = np.random.randn(1)
    
    print("Bobot awal:")
    print("W1:\n", W1)
    print("b1:\n", b1)
    print("W2:\n", W2)
    print("b2:\n", b2)
    print("-" * 50)
    
    for epoch in range(3):
        y_pred, hidden_output, hidden_input, final_input = forward_pass(X, W1, b1, W2, b2)
        
        dW2, db2, dW1, db1 = backward_pass(X, y_true, W1, b1, W2, b2, 
                                          hidden_output, hidden_input, final_input, y_pred)
        
        W2 -= learning_rate * dW2
        b2 -= learning_rate * db2
        W1 -= learning_rate * dW1
        b1 -= learning_rate * db1
        
        loss = mean_squared_error(y_pred, y_true)
        
        print(f"\nEpoch {epoch+1}:")
        print("Gradien:")
        print("dW1:\n", np.round(dW1, 6))
        print("db1:\n", np.round(db1, 6))
        print("dW2:\n", np.round(dW2, 6))
        print("db2:\n", np.round(db2, 6))
        print("\nBobot yang diupdate:")
        print("W1:\n", np.round(W1, 6))
        print("b1:\n", np.round(b1, 6))
        print("W2:\n", np.round(W2, 6))
        print("b2:\n", np.round(b2, 6))
        print(f"\nEpoch {epoch+1}, Loss: {loss:.6f}, Prediksi: {y_pred:.6f}")
        print("-" * 50)
        print("\n")  

train_regression_3epoch() 

Bobot awal:
W1:
 [[-1.74976547  0.3426804   1.1530358 ]
 [-0.25243604  0.98132079  0.51421884]
 [ 0.22117967 -1.07004333 -0.18949583]
 [ 0.25500144 -0.45802699  0.43516349]]
b1:
 [-0.58359505  0.81684707  0.67272081 -0.10441114]
W2:
 [[-0.53128038  1.02973269 -0.43813562 -1.11831825]]
b2:
 [1.61898166]
--------------------------------------------------

Epoch 1:
Gradien:
dW1:
 [[ 0.        0.       -0.      ]
 [ 0.197361  0.394722 -0.197361]
 [ 0.        0.       -0.      ]
 [ 0.        0.       -0.      ]]
db1:
 [0.       0.197361 0.       0.      ]
dW2:
 [[0.       0.385785 0.       0.      ]]
db2:
 0.191662

Bobot yang diupdate:
W1:
 [[-1.749765  0.34268   1.153036]
 [-0.272172  0.941849  0.533955]
 [ 0.22118  -1.070043 -0.189496]
 [ 0.255001 -0.458027  0.435163]]
b1:
 [-0.583595  0.797111  0.672721 -0.104411]
W2:
 [[-0.53128   0.991154 -0.438136 -1.118318]]
b2:
 [1.599815]

Epoch 1, Loss: 0.018367, Prediksi: 3.691662
--------------------------------------------------



Epoch 2:
Gr